version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    target-branch: 'develop'
  - package-ecosystem: 'pip'
    directory: '/python'
    schedule:
      interval: 'monthly'
    target-branch: 'develop'
