name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node

      - name: Install dependencies
        if: steps.release.outputs.release_created
        run: npm ci

      - name: Package VSIX
        if: steps.release.outputs.release_created
        run: npx vsce package --yarn

      - name: Publish on Visual Studio Code Extension Marketplace
        if: steps.release.outputs.release_created
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload VSIX to release assets
        if: steps.release.outputs.release_created
        run: |
          URL=$(echo "${{ steps.release.outputs.upload_url }}" | sed "s/[{][^)]*[}]//g")
          NAME="vscode-qt-for-python-${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.vsix"
          TARGET="${URL}?name=${NAME}"
          echo ${TARGET}
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/vsix" \
          --data-binary "@vscode-qt-for-python-${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.vsix" \
          ${TARGET}
