name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node

      - name: Install dependencies
        if: steps.release.outputs.release_created
        run: npm ci

      - name: Package VSIX
        if: steps.release.outputs.release_created
        run: npx vsce package --yarn

      - name: Publish on Visual Studio Code Extension Marketplace
        if: steps.release.outputs.release_created
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
